# Generated by Django 3.1.2 on 2020-12-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201215_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish_list',
        ),
    ]
