# Generated by Django 3.1.2 on 2020-12-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wish_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish_list',
        ),
    ]
